
services:
  postgres:
    image: postgres:13
    environment:
      POSTGRES_USER: airflow
      POSTGRES_PASSWORD: airflow
      POSTGRES_DB: airflow
    volumes:
      - postgres-db-volume:/var/lib/postgresql/data

  redis:
    image: redis:5
    command: ["redis-server", "--save", "", "--appendonly", "no"]

  zookeeper:
    image: confluentinc/cp-zookeeper:7.5.0
    environment:
      ZOOKEEPER_CLIENT_PORT: 2182
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - "2182:2182" 

  
  kafka:
    image: wurstmeister/kafka:latest
    environment:
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2182
      KAFKA_BROKER_ID: 1
      KAFKA_LISTENERS: INSIDE://0.0.0.0:9093,OUTSIDE://0.0.0.0:9094
      KAFKA_ADVERTISED_LISTENERS: INSIDE://kafka:9093,OUTSIDE://localhost:9094
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INSIDE:PLAINTEXT,OUTSIDE:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: INSIDE
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: 'true'
    ports:
      - "9093:9093"
      - "9094:9094"
    depends_on:
      - zookeeper

  # airflow-init:
  #   build: .
  #   depends_on:
  #     - postgres
  #     - redis
  #   environment:
  #     AIRFLOW__CORE__EXECUTOR: LocalExecutor
  #     AIRFLOW__CORE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow@postgres:5432/airflow
  #     AIRFLOW__CORE__FERNET_KEY: 4o6IAzy4IHJ23hZ8SLUR1gct1fc8quwL71yN8C5tdbA=
  #     AIRFLOW__CORE__LOAD_EXAMPLES: "false"
  #   volumes:
  #     - ./dags:/opt/airflow/dags
  #     - ./logs:/opt/airflow/logs
  #     - ./plugins:/opt/airflow/plugins
  #     - ./requirements.txt:/opt/airflow/requirements.txt
  #   command: ["bash", "-c", "pip install --no-cache-dir -r /opt/airflow/requirements.txt && airflow db init"]
  airflow-init:
    build: .
    depends_on:
      - postgres
      - redis
    environment:
      AIRFLOW__CORE__EXECUTOR: LocalExecutor
      AIRFLOW__CORE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow@postgres:5432/airflow
      AIRFLOW__CORE__FERNET_KEY: 4o6IAzy4IHJ23hZ8SLUR1gct1fc8quwL71yN8C5tdbA=
      AIRFLOW__CORE__LOAD_EXAMPLES: "false"
    volumes:
      - ./dags:/opt/airflow/dags
      - ./logs:/opt/airflow/logs
      - ./plugins:/opt/airflow/plugins
      - ./requirements.txt:/opt/airflow/requirements.txt
    command: >
      bash -c "pip install --no-cache-dir -r /opt/airflow/requirements.txt && airflow db init"
    restart: "no"

  airflow-webserver:
    build: .
    depends_on:
      - airflow-init
          # condition: 'service_completed_successfully'
      - kafka
    ports:
      - "8080:8080"
    environment:
      AIRFLOW__CORE__EXECUTOR: LocalExecutor
      AIRFLOW__CORE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow@postgres:5432/airflow
      AIRFLOW__CORE__FERNET_KEY: 4o6IAzy4IHJ23hZ8SLUR1gct1fc8quwL71yN8C5tdbA=
    env_file:
      - .env
    volumes:
      - ./dags:/opt/airflow/dags bsjsksjbxghfia
      - ./logs:/opt/airflow/logs
      - ./plugins:/opt/airflow/plugins
      - ./requirements.txt:/opt/airflow/requirements.txt
    command: ["bash", "-c", "pip install --no-cache-dir -r /opt/airflow/requirements.txt && airflow webserver"]

  airflow-scheduler:
    build: .
    depends_on:
      - airflow-init
      - kafka
    environment:
      AIRFLOW__CORE__EXECUTOR: LocalExecutor
      AIRFLOW__CORE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow@postgres:5432/airflow
      AIRFLOW__CORE__FERNET_KEY: 4o6IAzy4IHJ23hZ8SLUR1gct1fc8quwL71yN8C5tdbA=
    env_file:
      - .env
    volumes:
      - ./dags:/opt/airflow/dags
      - ./logs:/opt/airflow/logs
      - ./plugins:/opt/airflow/plugins
      - ./requirements.txt:/opt/airflow/requirements.txt
    command: ["bash", "-c", "pip install --no-cache-dir -r /opt/airflow/requirements.txt && airflow scheduler"]



volumes:
  postgres-db-volume:

networks:
  airflow-docker_default:
    external: true
